<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="9"
           failures="1"
           errors="0"
           skipped="0"
           time="98.407">
  <properties />
            <testcase name="TC01_LoginFirstAccount" time="38.074" classname="com.automation.testcase.TC_LoginTest">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	null"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	null
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
  com.automation.testcase.TC_LoginTest.TC01_LoginFirstAccount(TC_LoginTest.java:48)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
  org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
  org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
  org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
  org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
  org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:794)
  org.testng.TestRunner.run(TestRunner.java:596)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
  org.testng.SuiteRunner.run(SuiteRunner.java:276)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
  org.testng.TestNG.runSuites(TestNG.java:1063)
  org.testng.TestNG.run(TestNG.java:1031)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="TC01_LoginFirstAccount" time="7.558" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="8.723" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="6.750" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="7.640" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="5.073" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="5.594" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="10.248" classname="com.automation.testcase.TC_LoginTest" />
                <testcase name="TC01_LoginFirstAccount" time="8.747" classname="com.automation.testcase.TC_LoginTest" />
      
</testsuite>
